AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template for Cfn_networkstack_pipeline_sample

Parameters:
  CodeStarConnectionArn:
    Type: String
    Description: ARN of the CodeStar connection
    Default: arn:aws:codeconnections:ap-northeast-1:571634110936:connection/55c4e111-e74c-43c0-881d-e93c4fc6e41b
  CodePipelineArtifactStoreName:
    Type: String
    Default: codepipeline-ap-northeast-1-691348252728
    Description: Name of the existing S3 bucket for CodePipeline artifacts

Resources:
  CodePipelineServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: Cfn_pipeline_sample_CodePipelineServiceRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: Statement1
            Effect: Allow
            Principal:
              Service:
                - cloudformation.amazonaws.com
                - codepipeline.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: AWSCodeConnectionsFullAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "codestar-connections:*"
                Resource: "*"
        - PolicyName: S3AccessForCodePipeline
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:GetBucketVersioning
                  - s3:PutObject
                Resource:
                  - !Sub arn:aws:s3:::${CodePipelineArtifactStoreName}
                  - !Sub arn:aws:s3:::${CodePipelineArtifactStoreName}/*
        - PolicyName: CodeBuildAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - codebuild:StartBuild
                  - codebuild:BatchGetBuilds
                Resource:
                  - !Sub arn:aws:codebuild:${AWS::Region}:${AWS::AccountId}:project/Cfn_networkstack_pipeline_sample_Codebuild
                  - !Sub arn:aws:codebuild:${AWS::Region}:${AWS::AccountId}:project/Cfn_networkstack_pipeline_sample_DriftDetection

      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCodePipeline_FullAccess
        - arn:aws:iam::aws:policy/AWSCloudFormationFullAccess

  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: Cfn_pipeline_sample_CodeBuildServiceRole
      Path: /service-role/
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CodeBuildServiceRolePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Resource:
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/Cfn_networkstack_pipeline_sample_Codebuild
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/Cfn_networkstack_pipeline_sample_Codebuild:*
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/Cfn_networkstack_pipeline_sample_DriftDetection
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/Cfn_networkstack_pipeline_sample_DriftDetection:*
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
              - Effect: Allow
                Resource:
                  - arn:aws:s3:::codepipeline-ap-northeast-1-*
                  - arn:aws:s3:::Cfn_networkstack_pipeline_sample/*
                  - arn:aws:s3:::cfn-nested-sample
                  - arn:aws:s3:::cfn-nested-sample/*
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:GetBucketAcl
                  - s3:GetBucketLocation
              - Effect: Allow
                Action:
                  - codestar-connections:UseConnection
                Resource:
                  - !Ref CodeStarConnectionArn
              - Effect: Allow
                Action:
                  - codebuild:CreateReportGroup
                  - codebuild:CreateReport
                  - codebuild:UpdateReport
                  - codebuild:BatchPutTestCases
                  - codebuild:BatchPutCodeCoverages
                Resource:
                  - !Sub arn:aws:codebuild:${AWS::Region}:${AWS::AccountId}:report-group/Cfn_networkstack_pipeline_sample_Codebuild-*
              - Effect: Allow
                Action:
                  - codebuild:CreateReportGroup
                  - codebuild:CreateReport
                  - codebuild:UpdateReport
                  - codebuild:BatchPutTestCases
                  - codebuild:BatchPutCodeCoverages
                  - cloudformation:DetectStackResourceDrift
                  - cloudformation:ListStackResources
                Resource: !Sub arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/NetworkStack/*
              - Effect: Allow
                Action:
                  - cloudformation:DescribeStackDriftDetectionStatus
                  - cloudformation:DetectStackDrift
                  - cloudformation:DescribeStacks
                  - cloudformation:DescribeStackResources
                  - cloudformation:DescribeStackResourceDrifts
                  - cloudformation:DetectStackResourceDrift
                Resource: "*"
              - Effect: Allow
                Action:
                  - ec2:DescribeSubnets
                  - ec2:DescribeVpcs
                  - ec2:DescribeNetworkInterfaces
                  - ec2:DescribeSecurityGroups
                  - ec2:DescribeInstances
                  - ec2:DescribeNetworkAcls
                  - ec2:DescribeRouteTables
                  - ec2:DescribeVpcs
                  - ec2:DescribeVpcAttribute
                Resource: "*"

  NestedStackBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: cfn-networkstack-pipeline-sample-nestedtemplate
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  CodeBuild:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: Cfn_networkstack_pipeline_sample_Codebuild
      Description: CodeBuild project for Cfn_networkstack_pipeline_sample
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:5.0
        ImagePullCredentialsType: CODEBUILD
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspec.yml
      TimeoutInMinutes: 60
      QueuedTimeoutInMinutes: 480
      EncryptionKey: !Sub arn:aws:kms:${AWS::Region}:${AWS::AccountId}:alias/aws/s3
      LogsConfig:
        CloudWatchLogs:
          Status: ENABLED
        S3Logs:
          Status: DISABLED

  CodeBuildDriftDetection:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: Cfn_networkstack_pipeline_sample_DriftDetection
      Description: CodeBuild project for drift detection of Cfn_networkstack_pipeline_sample
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:5.0
        ImagePullCredentialsType: CODEBUILD
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspec_driftdetection.yml
      TimeoutInMinutes: 60
      QueuedTimeoutInMinutes: 480
      EncryptionKey: !Sub arn:aws:kms:${AWS::Region}:${AWS::AccountId}:alias/aws/s3
      LogsConfig:
        CloudWatchLogs:
          Status: ENABLED
        S3Logs:
          Status: DISABLED

  CfnSamplePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: Cfn_networkstack_pipeline_sample_pipeline
      RoleArn: !GetAtt CodePipelineServiceRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Ref CodePipelineArtifactStoreName
      PipelineType: V2
      ExecutionMode: QUEUED
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: "1"
              Configuration:
                ConnectionArn: !Ref CodeStarConnectionArn
                FullRepositoryId: becchi78/Cfn_networkstack_sample
                BranchName: develop
                DetectChanges: "true"
                OutputArtifactFormat: CODE_ZIP
              OutputArtifacts:
                - Name: SourceArtifact
              RunOrder: 1

        - Name: Build
          Actions:
            - Name: Build
              ActionTypeId:
                Category: Test
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              Configuration:
                ProjectName: !Ref CodeBuild
              InputArtifacts:
                - Name: SourceArtifact
              RunOrder: 1

        - Name: DriftDetection
          Actions:
            - Name: DriftDetection
              ActionTypeId:
                Category: Test
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              Configuration:
                ProjectName: !Ref CodeBuildDriftDetection
              InputArtifacts:
                - Name: SourceArtifact
              RunOrder: 1

        - Name: ChangeSets
          Actions:
            - Name: ChangeSets
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: "1"
              Configuration:
                ActionMode: CHANGE_SET_REPLACE
                Capabilities: CAPABILITY_IAM,CAPABILITY_NAMED_IAM
                ChangeSetName: ChangeSets-NetworkStack
                RoleArn: !GetAtt CodePipelineServiceRole.Arn
                StackName: NetworkStack
                TemplateConfiguration: SourceArtifact::param/parameters-pipeline.json
                TemplatePath: SourceArtifact::root-template.yaml
              InputArtifacts:
                - Name: SourceArtifact
              RunOrder: 1

        - Name: Approval
          Actions:
            - Name: Approval
              ActionTypeId:
                Category: Approval
                Owner: AWS
                Provider: Manual
                Version: "1"
              Configuration:
                CustomData: Please review the changes before proceeding with the changeset.
              RunOrder: 1

        - Name: Deploy
          Actions:
            - Name: Deploy
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: "1"
              Configuration:
                ActionMode: CREATE_UPDATE
                Capabilities: CAPABILITY_IAM,CAPABILITY_NAMED_IAM
                RoleArn: !GetAtt CodePipelineServiceRole.Arn
                StackName: PipelineNetworkStack
                TemplateConfiguration: SourceArtifact::param/parameters-pipeline.json
                TemplatePath: SourceArtifact::root-template.yaml
              InputArtifacts:
                - Name: SourceArtifact
              RunOrder: 1

Outputs:
  PipelineUrl:
    Description: CodePipeline URL
    Value: !Sub https://console.aws.amazon.com/codepipeline/home?region=${AWS::Region}#/view/${CfnSamplePipeline}
  BuildProjectUrl:
    Description: CodeBuild Project URL
    Value: !Sub https://console.aws.amazon.com/codesuite/codebuild/${AWS::AccountId}/projects/${CodeBuild}
  DriftDetectionProjectUrl:
    Description: Drift Detection CodeBuild Project URL
    Value: !Sub https://console.aws.amazon.com/codesuite/codebuild/${AWS::AccountId}/projects/${CodeBuildDriftDetection}
