AWSTemplateFormatVersion: "2010-09-09"
Description: "CloudFormation template for Infrastructure Stack Pipeline"

Parameters:
  StackName:
    Type: String
    Description: Name of the stack to be created/updated by this pipeline
  CodeStarConnectionArn:
    Type: String
    Description: ARN of the CodeStar connection
  CodePipelineArtifactStoreName:
    Type: String
    Description: Name of the existing S3 bucket for CodePipeline artifacts
  IAMStackName:
    Type: String
    Description: Name of the IAM stack
  RepositoryId:
    Type: String
    Description: Full repository ID for CodeStar connection
  BranchName:
    Type: String
    Description: Branch name for source code

Resources:
  CodeBuild:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub Cfn_${StackName}_pipeline_sample_UploadNestedStacks
      Description: !Sub CodeBuild project for Upload Nested Stacks of Cfn_${StackName}_pipeline_sample
      ServiceRole: !ImportValue
        Fn::Sub: "${IAMStackName}-CodeBuildServiceRoleArn"
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:5.0
        ImagePullCredentialsType: CODEBUILD
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspec.yml
      TimeoutInMinutes: 60
      QueuedTimeoutInMinutes: 480
      EncryptionKey: !Sub arn:aws:kms:${AWS::Region}:${AWS::AccountId}:alias/aws/s3
      LogsConfig:
        CloudWatchLogs:
          Status: ENABLED
        S3Logs:
          Status: DISABLED

  CodeBuildDriftDetection:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub Cfn_${StackName}_pipeline_sample_DriftDetection
      Description: !Sub CodeBuild project for drift detection of Cfn_${StackName}_pipeline_sample
      ServiceRole: !ImportValue
        Fn::Sub: "${IAMStackName}-CodeBuildServiceRoleArn"
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:5.0
        ImagePullCredentialsType: CODEBUILD
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspec_driftdetection.yml
      TimeoutInMinutes: 60
      QueuedTimeoutInMinutes: 480
      EncryptionKey: !Sub arn:aws:kms:${AWS::Region}:${AWS::AccountId}:alias/aws/s3
      LogsConfig:
        CloudWatchLogs:
          Status: ENABLED
        S3Logs:
          Status: DISABLED

  CfnSamplePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Sub Cfn_${StackName}_sample_pipeline
      RoleArn: !ImportValue
        Fn::Sub: "${IAMStackName}-CodePipelineServiceRoleArn"
      ArtifactStore:
        Type: S3
        Location: !Ref CodePipelineArtifactStoreName
      PipelineType: V2
      ExecutionMode: QUEUED
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: "1"
              Configuration:
                ConnectionArn: !Ref CodeStarConnectionArn
                FullRepositoryId: !Ref RepositoryId
                BranchName: !Ref BranchName
                DetectChanges: "true"
                OutputArtifactFormat: CODE_ZIP
              OutputArtifacts:
                - Name: SourceArtifact
              RunOrder: 1

        - Name: UploadNestedStacks
          Actions:
            - Name: UploadNestedStacks
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              Configuration:
                ProjectName: !Ref CodeBuild
              InputArtifacts:
                - Name: SourceArtifact
              RunOrder: 1

        - Name: DriftDetection
          Actions:
            - Name: DriftDetection
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              Configuration:
                ProjectName: !Ref CodeBuildDriftDetection
              InputArtifacts:
                - Name: SourceArtifact
              RunOrder: 1

        - Name: ChangeSets
          Actions:
            - Name: ChangeSets
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: "1"
              Configuration:
                ActionMode: CHANGE_SET_REPLACE
                Capabilities: CAPABILITY_IAM,CAPABILITY_NAMED_IAM
                ChangeSetName: !Sub "ChangeSets-${StackName}"
                RoleArn: !ImportValue
                  Fn::Sub: "${IAMStackName}-CodePipelineServiceRoleArn"
                StackName: !Ref StackName
                TemplateConfiguration: SourceArtifact::parameters/parameters.json
                TemplatePath: SourceArtifact::templates/root-template.yaml
              InputArtifacts:
                - Name: SourceArtifact
              RunOrder: 1

        - Name: Approval
          Actions:
            - Name: Approval
              ActionTypeId:
                Category: Approval
                Owner: AWS
                Provider: Manual
                Version: "1"
              Configuration:
                CustomData: Please review the changes before proceeding with the changeset.
              RunOrder: 1

        - Name: Deploy
          Actions:
            - Name: Deploy
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: "1"
              Configuration:
                ActionMode: CHANGE_SET_EXECUTE
                ChangeSetName: !Sub "ChangeSets-${StackName}"
                RoleArn: !ImportValue
                  Fn::Sub: "${IAMStackName}-CodePipelineServiceRoleArn"
                StackName: !Ref StackName
              RunOrder: 1

Outputs:
  CodeBuildProjectName:
    Description: Name of the CodeBuild Project
    Value: !Ref CodeBuild
  CodeBuildDriftDetectionProjectName:
    Description: Name of the CodeBuild Drift Detection Project
    Value: !Ref CodeBuildDriftDetection
  CodePipelineName:
    Description: Name of the CodePipeline
    Value: !Ref CfnSamplePipeline
